version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-2.7
      - test-3.4
      - test-3.5
      - test-3.6
      - test-3.7
jobs:
  test_3.6: &test-template
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run: pip install .
      - run: pip install pytest pytest-cov flake8
      - run: pytest --cov=pyunc tests
      - run: flake8 pyunc

  test_2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie

  test_3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4-jessie

  test_3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie

  test_3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7-jessie
