version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.7
      - test-3.6
      - test-3.5
      - test-3.4
      - test-2.7

jobs:
  test-3.7: &test-template
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run: pip install .
      - run: pip install pytest pytest-cov flake8
      - run: pytest --cov=pyunc tests
      - run: flake8 pyunc

  test-3.6:
    <<: *test-template
    docker:
      - image: circleci/python:3.6-jessie

  test-3.5:
    <<: *test-template
    docker:
      - image: circleci/python:3.5-jessie

  test-3.4:
    <<: *test-template
    docker:
      - image: circleci/python:3.4-jessie

  test-2.7:
    <<: *test-template
    docker:
      - image: circleci/python:2.7-jessie
